package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/standalone/multipleRoots.html

type multipleRoots struct {
	Roots []*dom.Element
}

func newMultipleRoots() *multipleRoots {
	li0 := _document.CreateElement("li", nil)
	const stringliteral0 = "hello"
	li0.SetTextContent(&stringliteral0)
	li1 := _document.CreateElement("li", nil)
	const stringliteral1 = "world"
	li1.SetTextContent(&stringliteral1)
	return &multipleRoots{
		Roots: []*dom.Element{li0, li1},
	}
}

// source: testdata/include/includeMultipleRoots.html

type includeMultipleRoots struct {
	Roots []*dom.Element
}

func newIncludeMultipleRoots() *includeMultipleRoots {
	div0 := _document.CreateElement("div", nil)
	include0 := newMultipleRoots()
	for _, r := range include0.Roots {
		div0.AppendChild(&r.Node)
	}
	return &includeMultipleRoots{
		Roots: []*dom.Element{div0},
	}
}

// source: testdata/include/multilevel.html

type multilevel struct {
	Roots []*dom.Element
}

func newMultilevel() *multilevel {
	div0 := _document.CreateElement("div", nil)
	include0 := newIncludeMultipleRoots()
	for _, r := range include0.Roots {
		div0.AppendChild(&r.Node)
	}
	return &multilevel{
		Roots: []*dom.Element{div0},
	}
}
