package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/standalone/Exported.html

type Exported struct {
	Roots []*dom.Element
}

func NewExported() *Exported {
	div0 := _document.CreateElement("div", nil)
	div0.SetAttribute("class", "Exported")
	return &Exported{
		Roots: []*dom.Element{div0},
	}
}
