package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/standalone/multipleRoots.html

type multipleRoots struct {
	roots []*dom.Element
}

func newMultipleRoots() *multipleRoots {
	li0 := _document.CreateElement("li", nil)
	const stringliteral0 = "hello"
	li0.SetTextContent(&stringliteral0)
	li1 := _document.CreateElement("li", nil)
	const stringliteral1 = "world"
	li1.SetTextContent(&stringliteral1)
	return &multipleRoots{
		roots: []*dom.Element{li0, li1},
	}
}

func (v *multipleRoots) Roots() []*dom.Element {
	return v.roots
}
