package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/single/self_closing.html

type self_closing struct {
	roots []*dom.Element
}

func newSelf_closing() *self_closing {
	img0 := _document.CreateElement("img", nil)
	img0.SetAttribute("src", "dog.png")
	return &self_closing{
		roots: []*dom.Element{img0},
	}
}
