package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/single/specific_element.html

type specific_element struct {
	roots []*dom.Element
}

func newSpecific_element() *specific_element {
	div0 := _document.CreateElement("div", nil)
	audio0 := _document.CreateElement("audio", nil)
	div0.AppendChild(&audio0.Node)
	return &specific_element{
		roots: []*dom.Element{div0},
	}
}
