package ui

// Code generated by nausicaa. DO NOT EDIT.

import (
	"github.com/gowebapi/webapi"
	"github.com/gowebapi/webapi/dom"
	"github.com/gowebapi/webapi/html"
	"github.com/gowebapi/webapi/html/canvas"
	"github.com/gowebapi/webapi/html/media"
)

type (
	_ *webapi.Document // prevent unused import errors
	_ *dom.Element
	_ *html.HTMLDivElement
	_ *canvas.HTMLCanvasElement
	_ *media.HTMLAudioElement
)

var (
	_document = webapi.GetDocument()
)

// source: testdata/standalone/unexported.html

type unexported struct {
	roots []*dom.Element
}

func newUnexported() *unexported {
	div0 := _document.CreateElement("div", nil)
	div0.SetAttribute("class", "unexported")
	return &unexported{
		roots: []*dom.Element{div0},
	}
}

func (v *unexported) Roots() []*dom.Element {
	return v.roots
}
